### ISSUE TITLE
Exclude items from reservation

### ISSUE THREAD

**Issue by Thomasov** [aSetback/GoodBot#10]
Feature request, it would be very useful if you could set it up so certain items are excluded from being reserved. If there's a way to do this currently I haven't been able to find it. Everything else is working perfectly, thanks for a great bot.

**Comment by davedehaan** [comment]
@Thomasov Sounds good -- help me understand how you'd like this to work?  I agree it would be a useful feature to add/remove specific items to specific raids, but I'm stuck on the scope --
Is this a server-wide feature?  Our specific to a single raid?

I think this will depend a lot on the specific use case -- is the idea to be able to hard reserve a specific item for a raid?  eg, `+hardreserve bindings of the windseeker`, or is the intention to allow no one on the server to reserve the tiger in ZG, or something of that nature?

**Comment by Thomasov** [comment]
More so the hard reserve, so if we want to take bindings off the table as you have mentioned above we have a mechanism to do so. Whether it's server level or raid level doesn't matter too much as long as the permissions are locked down to only users with manage channel permission like you've done for other commands.
