### ISSUE TITLE
Valid name check

### ISSUE THREAD

**Issue by Drakehawk5000** [aSetback/GoodBot#19]
Feature request (but more like a question at first).

Why are accents and special characters not allowed on Characters (Toons) names?

Some of my characters have special chars on their names (like ø or í) and I've to clarify that on each pug I sign in so I'll not be excluded since they couldnt find my toon. Since the game itself allow those kind of names (and discord too), there is any particular reason why they're not accepted here?

Thanks!

**Comment by aSetback** [comment]
@Drakehawk5000 
Here's the regex I use for determining the validity of a name.  Most special characters are allowed, this is supposed to be the same as blizzard uses.  Which characters are you using that are not included?
`var reg = /^[a-zàâäåªæÆçÇœŒÐéèêëËƒíìîïÏñÑóòôöõºúùûÜýÿß]+$/i;`

**Comment by Drakehawk5000** [comment]
This one for example does not pass:

`Jøsephine`
